foreground #dee7ec
background #0b0f11
cursor #b4cad6
cursor_text_color #0b0f11
selection_foreground #0b0f11
selection_background #b4cad6
color0 #343434
color1 #8383ff
color2 #40dfee
color3 #75fcdd
color4 #7cb2c8
color5 #7baeea
color6 #83d5e7
color7 #ccdcd6
color8 #9aa59f
color9 #a29eff
color10 #66f0ff
color11 #c9fff3
color12 #a6c6d1
color13 #a2c0f7
color14 #8ae9fc
color15 #ffffff
